version: '3'


services:
  sqc-back:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - "8000:8000"

    depends_on:
      - mongoDB


  mongoDB:
    image: mongo

    ports:
      - '27017:27017'
    volumes:
      - ./mongoDB:/data/db

    restart: always
